# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 016733a5c4f9325c8b0406aadd1a471de4a0f99015c2677d9d0ec68860cbe1364ab32b3effb9550be8589eabff648a7cb386dd5e71912c6636f535a670bf8532

test:
  secret_key_base: c72638aa1332d704d667b4b46dbba0f5e0d48f7bf47c0c21a570c7bfd994f5a4e9399321097edd9ec7141955005556d58f995e360fc9bcae76c6e20bf8ea3c1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
